spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fooddelivery
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        dialect:spring.jpa.properties.hibernate.dialect
        ddl-auto=update
    show-sql: true
    
server:
  port: 9006
  servlet:
    context-path: /api