spring:
  datasource:
    url: jdbc:mysql://localhost:3306/zee5appjpa
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        dialect:spring.jpa.properties.hibernate.dialect
    show-sql: true
    
    hibernate:
      naming:
        physical-strategy: com.zee.zee5app.utils.CustomNamingStrategy
      ddl-auto: update
server:
  port: 9006
  
zee5app:
  app:
    jwtSecret: secretkey
    jwtExpirationMs: 86400000